FROM tomcat:9-jdk11-openjdk-slim

# Remove default Tomcat applications except manager and host-manager
RUN rm -rf /usr/local/tomcat/webapps/* && \
    mv /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager && \
    mv /usr/local/tomcat/webapps.dist/host-manager /usr/local/tomcat/webapps/host-manager

EXPOSE 8080

CMD ["catalina.sh", "run"]
