FROM tomcat:9-jdk11-openjdk-slim

# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy manager and host-manager from webapps.dist to webapps
RUN cp -R /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/ && \
    cp -R /usr/local/tomcat/webapps.dist/host-manager /usr/local/tomcat/webapps/

# Copy your custom tomcat-users.xml file
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
RUN ls -l /usr/local/tomcat/conf/tomcat-users.xml

# Copy custom context.xml to disable IP restriction for manager app
COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
RUN ls -l /usr/local/tomcat/webapps/manager/META-INF/context.xml

EXPOSE 8080

CMD ["catalina.sh", "run"]

