services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - ${HTTP_PORT}
    volumes:
      #Mount you web app here
      #./mywebapp.war:/usr/tomcat/webapps
      - ./config/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
