services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mariadb_data:
